// ─────────────────────────────────────────────
// reportHelpers.js  –  EduPoll Shared Helpers
// ─────────────────────────────────────────────
import { COLORS, PAGE } from './reportStyles.js';

/**
 * Draw the branded page header on the current jsPDF page.
 * @param {import('jspdf').jsPDF} doc
 * @param {number} pageNum  Current page number
 * @param {number} totalPages Total page count (pass 0 while building, patch later)
 * @param {Date}   generatedAt
 */
export function drawPageHeader(doc, pageNum, totalPages, generatedAt) {
  const { margin, width } = PAGE;

  // Dark-blue banner
  doc.setFillColor(...COLORS.headerBg);
  doc.roundedRect(margin, 6, width - margin * 2, 22, 3, 3, 'F');

  // Logo circle
  doc.setFillColor(250, 204, 21); // yellow
  doc.circle(margin + 10, 17, 7, 'F');
  doc.setFillColor(255, 255, 255);
  doc.circle(margin + 10, 17, 4, 'F');
  doc.setFillColor(250, 204, 21);
  doc.circle(margin + 10, 17, 2, 'F');

  // EDUPOLL text
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(14);
  doc.setTextColor(...COLORS.headerText);
  doc.text('EDUPOLL', margin + 20, 15);

  // Subtitle
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(7);
  doc.text('Smart Polling. Better Learning.', margin + 20, 21);

  // Right side title
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('CLASSROOM POLL REPORT', width - margin - 2, 15, { align: 'right' });

  // Date-time on right
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6.5);
  doc.text(
    `Generated: ${generatedAt.toLocaleDateString('en-IN', { day: '2-digit', month: 'short', year: 'numeric' })} ${generatedAt.toLocaleTimeString('en-IN', { hour: '2-digit', minute: '2-digit' })}`,
    width - margin - 2, 21,
    { align: 'right' }
  );

  return 32; // y position after header
}

/**
 * Draw the page footer on the current jsPDF page.
 * @param {import('jspdf').jsPDF} doc
 * @param {number} pageNum
 * @param {number} totalPages
 */
export function drawPageFooter(doc, pageNum, totalPages) {
  const { margin, width, height } = PAGE;
  const y = height - 10;

  doc.setDrawColor(...COLORS.border);
  doc.setLineWidth(0.3);
  doc.line(margin, y - 4, width - margin, y - 4);

  // Left – branding
  doc.setFillColor(250, 204, 21);
  doc.circle(margin + 3, y - 1, 2.5, 'F');
  doc.setFillColor(255, 255, 255);
  doc.circle(margin + 3, y - 1, 1.4, 'F');

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(6.5);
  doc.setTextColor(...COLORS.textDark);
  doc.text('Generated by EduPoll', margin + 7, y - 2.5);
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(6);
  doc.setTextColor(...COLORS.textMuted);
  doc.text('Smart Polling. Better Learning.', margin + 7, y + 0.5);

  // Right – page number
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(7);
  doc.setTextColor(...COLORS.textDark);
  doc.text(`Page ${pageNum} of ${totalPages}`, width - margin - 2, y - 1, { align: 'right' });
}

/**
 * Utility: wrap long text for jsPDF.
 */
export function wrapText(doc, text, maxWidth) {
  return doc.splitTextToSize(String(text || ''), maxWidth);
}

/**
 * Compute per-option groups from the results object returned by the API.
 * Returns: { optionGroups: [{label, students}], notResponded: [] }
 */
export function groupByOption(results) {
  const answered = results?.answered || [];
  const notAnswered = results?.notAnswered || [];

  const map = {};
  for (const s of answered) {
    const key = s.choice || 'Other';
    if (!map[key]) map[key] = [];
    map[key].push(s);
  }

  const optionGroups = Object.entries(map).map(([label, students]) => ({
    label,
    students,
  }));

  return { optionGroups, notResponded: notAnswered };
}
